Create preliminary Docker sandbox setup
rocketden/tester pull request #1
Opened 2020-11-13 09:32 UTC by alankbi

### List of Changes

* Set up basic route for users to submit bash commands
* Create docker file setup and code to initialize and run disposable sandbox containers
* Return output of commands to user

### Notes

* This is a very preliminary proposed structure for the Docker setup, so I'm open to changing anything
* Some of the docker setup can be confusing so it may be worthwhile going over it in a call
* Lots of features are missing in this PR including tests, error handling, security checks, etc.

2020-11-13 09:35 UTC, alankbi commented
![](https://github.trello.services/images/mini-trello-icon.png) [Look into basic tester + docker setup](https://trello.com/c/ugMSg2gE/192-look-into-basic-tester-docker-setup)

2020-12-28 03:10 UTC, zpChris commented
Is their a Docker account attached to this @alankbi -- if so, add the account details in GDrive?

2020-12-31 21:48 UTC, jerry1ye10 commented
Put together the docker command from the code: docker run --rm /Users/jerryye/rocketden/tester/src/main/java/com/rocketden/tester/temp/folder12345:/app/code -t rocketden/tester

2020-12-31 21:56 UTC, jerry1ye10 commented
Need to manually run build.sh to get it working ```sh build.sh```

Might be worth to move out of the java directory as well? Not sure how its normally structured though

2021-01-03 16:15 UTC, zpChris requested changes
I am requesting changes, but really I don't have many changes -- just a few nits, but mostly questions to make sure I understand how this works correctly.

One more broad question -- is the use of the `DockerService.java` class and the corresponding `spawnAndRun` method to essentially mimic the work of the `start.sh` script, but in a callable Java form?

2021-01-03 16:15 UTC, zpChris commented on src/main/java/com/rocketden/tester/service/DockerService.java
> +        int exitVal = process.waitFor();
Per [this Stack Overflow article](https://stackoverflow.com/questions/5483830/process-waitfor-never-returns), we may want to attach a timeout to this.

Also, it seems like this returns a boolean value -- is there a reason that `exitVal` and the `runDto` `status` variable is an `int`? Is that perhaps looking forward to when we may have other statuses?

2021-01-03 16:15 UTC, zpChris commented on src/main/java/com/rocketden/tester/service/DockerService.java
> +                InputStreamReader(process.getInputStream()));
So the output that we want to capture is the input stream of the process?

I'm confused by this -- are there any links that explain how this is the case?

2021-01-03 16:15 UTC, zpChris commented on src/main/java/com/rocketden/tester/service/RunnerService.java
> +        RunDto output = dockerService.spawnAndRun(folder);
If `output` equals `null`, should we return an error instead of just `null`? I'm uncertain what this may look like, maybe `status` could equal a special value, but I figure for the future we may need better error reporting.

2021-01-03 16:15 UTC, zpChris commented on src/main/java/com/rocketden/tester/service/SetupService.java
> +                Files.write(Paths.get(driverFile), code.getBytes(StandardCharsets.UTF_8));
So right now, we are directly executing the user's code; however, for the future, this is where additional work may be done in combining the test cases with the user's code, potentially adding any necessary libraries / OS / etc, and building any necessary objects to run the code. Can you confirm whether that's correct?

2021-01-03 16:18 UTC, zpChris commented
I also left some comments on the Postman request, since I'm not sure it's working as expected.

2021-01-04 02:37 UTC, alankbi commented on src/main/java/com/rocketden/tester/docker/build.sh
> +#!/bin/bash
[This post](https://stackoverflow.com/questions/23735149/what-is-the-difference-between-a-docker-image-and-a-container) helped me a bit - as for the commands, for the first one, it's basically building an image with the tag name as 'rocketden/tester' off of the directory `../docker`. 

The second command I found online to delete/clean up temp images that are created during the build process, which you can check using the `docker images` command

2021-01-04 02:39 UTC, alankbi commented on .mvn/wrapper/MavenWrapperDownloader.java
> +        File baseDirectory = new File(args[0]);
I'm not sure - this file I copied straight from the [main repo](https://github.com/rocketden/main/blob/master/.mvn/wrapper/MavenWrapperDownloader.java) - I think it's just some setup file to get Maven working.

2021-01-04 02:40 UTC, alankbi commented on README.md
> +* Run `build.sh` in the `docker` folder any time you make changes to files in that folder
Maybe try `bash build.sh`? That's the command I use and I don't get any modified files showing up

2021-01-04 02:41 UTC, alankbi commented on src/main/java/com/rocketden/tester/docker/start.sh
> +fi
Yep that's my understanding as well :)

2021-01-04 02:43 UTC, alankbi commented on pom.xml
>  			<artifactId>lombok</artifactId>
Sounds good - made it 2 spaces as well to keep consistent with the main repo

2021-01-04 02:44 UTC, alankbi commented on tester.iml
>  </module>
Sounds good - will add that this is an auto-generated file so the change may or may not be overridden in the future

2021-01-04 02:46 UTC, alankbi commented on src/main/java/com/rocketden/tester/dto/RunDto.java
> +    private int status;
As of now it holds the exit status of the bash script - however I think that probably change in the future when we add all the languages and set up a proper scoring system

2021-01-04 02:47 UTC, alankbi commented on src/main/java/com/rocketden/tester/dto/RunDto.java
> +    private String output;
Right now it holds the output of the command that they run - in the future maybe this could be useful for like showing diffs between the expected and actual output?

2021-01-04 02:49 UTC, alankbi commented on src/main/java/com/rocketden/tester/docker/Dockerfile
> +WORKDIR /app
From my understanding this is the directory where the files will be created/located inside of the docker containers, so we won't actually see this anywhere unless we inspect the contents of the containers for some purpose

2021-01-04 02:50 UTC, alankbi commented on src/main/java/com/rocketden/tester/docker/build.sh
> +docker rmi `docker images -f "dangling=true" -q`
Could you try running this with `bash build.sh`? That fixed the issue for me

2021-01-04 02:54 UTC, alankbi commented on src/main/java/com/rocketden/tester/docker/start.sh
> +docker run --rm -v "$PWD/../temp/$1:/app/code" -t rocketden/tester
`docker run` is the command that creates and starts a docker container, where `-t rocketden/tester` specifies which image (i.e. like which template) to create it from. The `--rm` is is basically to delete the container after it finishes running, and the `-v <local_path>:<docker_path>` is specifying to create a "mounted" container that copies the contents of `local_path` (for us the temp folders) into the specified `docker_path` folder on the containers

2021-01-04 02:59 UTC, alankbi commented on src/main/java/com/rocketden/tester/service/SetupService.java
> +                System.out.println("An error occurred");
Sounds good - also want to note that I think we'll be changing these in the future to the `ApiError` system that we have in the main repo so that should also fix it

2021-01-04 03:02 UTC, alankbi commented on src/main/java/com/rocketden/tester/service/DockerService.java
> +        int exitVal = process.waitFor();
That's a good point - if it's cool, I've added a card to the backlog for that so that we can do it in another PR to help with size (and also in case we end up changing this code altogether when adding in the different languages)

2021-01-04 03:14 UTC, alankbi commented on src/main/java/com/rocketden/tester/service/DockerService.java
> +        int exitVal = process.waitFor();
Actually I just realized when looking into your second point that you're right - there's a second method that returns a boolean _and_ allows you to easily specify a timeout, so I've just added that to this PR

2021-01-04 03:17 UTC, alankbi commented on src/main/java/com/rocketden/tester/service/DockerService.java
> +                InputStreamReader(process.getInputStream()));
Yeah that was confusing to me too when found the code to capture the output - I just found [this post](https://stackoverflow.com/questions/1830698/what-is-inputstream-output-stream-why-and-when-do-we-use-them) tho and it sounds like input streams are for reading content (hence reading the output of the commands) and output streams are for actually writing stuff to files and stuff

2021-01-04 03:22 UTC, alankbi commented on src/main/java/com/rocketden/tester/service/RunnerService.java
> +        RunDto output = dockerService.spawnAndRun(folder);
Yeah I think it it's null then it would make sense to throw an error - I updated the `spawnAndRun` method to return null in the catch block rather than at the end of the method so now if it ever returns null it should also print an error message (not the same as throwing an error but my logic is that we can do that once we add in the ApiError stuff which wasn't included in this PR)

2021-01-04 03:26 UTC, alankbi commented on src/main/java/com/rocketden/tester/service/SetupService.java
> +                Files.write(Paths.get(driverFile), code.getBytes(StandardCharsets.UTF_8));
Yeah I think so - that's where things in my mind get complicated, since somehow we have to take in the user code, test cases, possibly solution code, and then for each different language, generate a different script to parse the test cases, call the user's dynamic method with each test case, and compare/capture the output

2021-01-04 03:43 UTC, alankbi commented
>Might be worth to move out of the java directory as well? Not sure how its normally structured though

The main reason I put them there was to avoid long relative paths in the commands (e.g. `docker build src/main/.../docker`), however I'd be totally fine to move it too - were you thinking like a folder in the root directory or someplace else?

>One more broad question -- is the use of the DockerService.java class and the corresponding spawnAndRun method to essentially mimic the work of the start.sh script, but in a callable Java form?

Yeah pretty much, that's a good way to think about it

2021-01-04 16:18 UTC, zpChris commented on .mvn/wrapper/MavenWrapperDownloader.java
> +        File baseDirectory = new File(args[0]);
Ok gotcha, thanks -- I'll leave this file be then.

2021-01-04 16:39 UTC, zpChris commented on README.md
> +* Run `build.sh` in the `docker` folder any time you make changes to files in that folder
You're right that works -- I'll use that command instead in the future.

2021-01-04 16:43 UTC, zpChris commented on src/main/java/com/rocketden/tester/docker/build.sh
> +#!/bin/bash
The directory `../docker` is just the current folder right? I could be wrong but I think that could be `./` or `/` -- works either way though.

2021-01-04 16:46 UTC, zpChris commented on src/main/java/com/rocketden/tester/dto/RunDto.java
> +    private String output;
That makes sense -- and yeah, I think that your thoughts for future development sounds good.

2021-01-04 16:48 UTC, zpChris commented on src/main/java/com/rocketden/tester/docker/Dockerfile
> +WORKDIR /app
This may be beyond the scope of what we need to understand, but will we need to be able to look inside these containers?

2021-01-04 16:49 UTC, zpChris commented on src/main/java/com/rocketden/tester/docker/build.sh
> +docker rmi `docker images -f "dangling=true" -q`
That fixed the `git status` issue mentioned elsewhere, but unfortunately not the issue here.

<img width="485" alt="Running with Bash Build.sh" src="https://user-images.githubusercontent.com/7987279/103558562-b929f780-4e69-11eb-8e25-016b8cb75082.png">

2021-01-04 16:53 UTC, zpChris commented on src/main/java/com/rocketden/tester/docker/start.sh
> +docker run --rm -v "$PWD/../temp/$1:/app/code" -t rocketden/tester
Thank you!

2021-01-04 16:54 UTC, zpChris commented on src/main/java/com/rocketden/tester/service/SetupService.java
> +                System.out.println("An error occurred");
Ok cool, sounds great!

2021-01-04 16:56 UTC, zpChris commented on src/main/java/com/rocketden/tester/service/DockerService.java
> +        int exitVal = process.waitFor();
Awesome, thanks!

How about the second question -- to confirm, are we leaving it an `int` because we may add more status options in the future?

2021-01-04 17:01 UTC, zpChris commented on src/main/java/com/rocketden/tester/service/RunnerService.java
> +        RunDto output = dockerService.spawnAndRun(folder);
That works by me!

2021-01-04 17:02 UTC, zpChris commented on src/main/java/com/rocketden/tester/service/SetupService.java
> +                Files.write(Paths.get(driverFile), code.getBytes(StandardCharsets.UTF_8));
That's a good list though, I think at least we know what we need to tackle (if we are indeed thinking about this correctly).

2021-01-04 17:09 UTC, zpChris approved these changes
LGTM! Just left one last very small nit (and extended the conversion on a few of the previous comments).

2021-01-04 17:09 UTC, zpChris commented on src/main/java/com/rocketden/tester/service/DockerService.java
> +    private final static int TIME_LIMIT = 2;
nit:
```suggestion
    private static final int TIME_LIMIT = 2;
```
Based on the following warning:
<img width="1181" alt="Order of Static and Final" src="https://user-images.githubusercontent.com/7987279/103560305-6867ce00-4e6c-11eb-845e-c71c06438687.png">

2021-01-04 18:36 UTC, alankbi commented on src/main/java/com/rocketden/tester/docker/Dockerfile
> +WORKDIR /app
Idk if we will need to, but at the very least if we do I think we can do some [ssh](https://stackoverflow.com/questions/30172605/how-do-i-get-into-a-docker-containers-shell) type stuff

2021-01-04 18:46 UTC, alankbi commented on src/main/java/com/rocketden/tester/docker/build.sh
> +docker rmi `docker images -f "dangling=true" -q`
Hm ok, I ended up just deleting that command since after updating my Docker, I no longer get the issue with temp images needing to be deleted (and hence the command shows the error you see above)

2021-01-04 18:48 UTC, zpChris commented on src/main/java/com/rocketden/tester/docker/build.sh
> +docker rmi `docker images -f "dangling=true" -q`
Does that mean that we should delete the `docker rmi` line?

2021-01-04 18:48 UTC, alankbi commented on src/main/java/com/rocketden/tester/docker/build.sh
> +#!/bin/bash
I ended up moving the build.sh and start.sh files to a scripts folder which should help make it more clear and also ends up resolving that problem (since now we do in fact need the `../docker` since they're in different folders)

2021-01-04 18:49 UTC, alankbi commented on src/main/java/com/rocketden/tester/docker/build.sh
> +docker rmi `docker images -f "dangling=true" -q`
Yeah I've already deleted it (just have to push my changes)

2021-01-06 18:10 UTC, jerry1ye10 approved these changes

2021-01-08 05:06 UTC, merged