Serialize outputs in a structured and documented form
rocketden/tester pull request #11
Opened 2021-01-30 08:45 UTC by alankbi

### List of Changes:

* Create delimiters to separate driver program test cases and outputs
* Implement serialization method for printing return objects in Java and Python
* Update README with up-to-date info on new serialization format
* Add new tests to cover the `getToStringCode` method 

### Notes:

* We originally decided to just compare the serialized strings to judge outputs, but I feel like this may be too difficult to deal with. Mainly, I think it would require us to serialize every object type in each language exactly the same, as well as ensure that when people create problem outputs (i.e. the correct answers), they also manually follow the same format, which just seems a bit too rigid of a system
* As a result I'm thinking it would be good if we read in the serialized objects (again using JSON, possibly reusing the private InputParser method since it's all the same format) - however I'm open to talking about this and seeing what would actually be best

2021-01-30 08:48 UTC, alankbi commented
![](https://github.trello.services/images/mini-trello-icon.png) [Serialize outputs in a structured and documented form](https://trello.com/c/jtlItrKo/253-serialize-outputs-in-a-structured-and-documented-form)

2021-01-30 21:06 UTC, zpChris requested changes
This largely looks good to me! Requesting changes just because there are a few nits and questions.

2021-01-30 21:06 UTC, zpChris commented on src/main/java/com/rocketden/tester/service/generators/PythonDriverGeneratorService.java
>      }
Is this still to-be-implemented? I notice you don't use the `outputType` parameter.

2021-01-30 21:06 UTC, zpChris commented on src/test/java/com/rocketden/tester/api/JavaTests.java
> +                "###########_SUCCESS_############",
Replace these with the `OutputParser.DELIMITER_XXX` variables, so that if we change any of those delimiters we don't have to change all the test cases as well.

(Same goes for the other files.)

2021-01-30 21:06 UTC, zpChris commented on src/test/java/com/rocketden/tester/service/generators/JavaDriverGeneratorServiceTests.java
> +                "    }");
I'm guessing you prefer using spaces instead of the `\t` for tabs, to improve readability?

2021-01-30 21:06 UTC, zpChris commented on src/test/java/com/rocketden/tester/service/generators/PythonDriverGeneratorServiceTests.java
> +    }
Is tis test necessary? It's not actually changing yet based on the parameter, right?

2021-01-31 09:49 UTC, alankbi commented on README.md
> +    }
1. The way it currently works (open to changes) is that the serialize method is dynamically generated so the param type matches what the output type is - and then of course the body of the method changes too depending on that output type
2. I updated the README to reflect the actual format of the Java toString methods, however, I also wanted to bring up the note in the description and see what your thoughts were on that: 

> We originally decided to just compare the serialized strings to judge outputs, but I feel like this may be too difficult to deal with. Mainly, I think it would require us to serialize every object type in each language exactly the same, as well as ensure that when people create problem outputs (i.e. the correct answers), they also manually follow the same format, which just seems a bit too brittle of a system

> As a result I'm thinking it would be good if we read in the serialized objects (again using JSON, possibly reusing the private InputParser method since it's all the same format) - however I'm open to talking about this and seeing what would actually be best

So as of now the README only has example serializations (as opposed to ground truth) - for example Python produces lists as `['a', 'b']` rather than `[a, b]`

2021-01-31 09:49 UTC, alankbi commented on src/main/java/com/rocketden/tester/service/generators/JavaDriverGeneratorService.java
> +        }
Addressed in other comment

2021-01-31 09:54 UTC, alankbi commented on src/main/java/com/rocketden/tester/service/generators/PythonDriverGeneratorService.java
>      }
Based on the current plan I had in mind (JSON format read in using Gson to compare the objects) this would be the implementation haha (strings, numbers, and lists are all properly formatted when printed, booleans are uppercase but Gson is able to parse that)

I think we can have a discussion on what route we want to go with in terms of judging outputs so this can change if need be

2021-01-31 09:57 UTC, alankbi commented on src/test/java/com/rocketden/tester/service/generators/JavaDriverGeneratorServiceTests.java
> +                "    }");
Yes haha - I do feel like it helps with clarity/productivity to be able to see the generated code formatted nicely (although this is a pretty small personal pref so we can talk about standardization if need be)

2021-01-31 09:58 UTC, alankbi commented on src/test/java/com/rocketden/tester/service/generators/PythonDriverGeneratorServiceTests.java
> +    }
Yeah the method itself is the same, so having these 3 assertions was just to make sure they all stayed the same. This might be repetitive so I'd be happy to remove it down to one assertion only, however I do want to keep this test since I think it's worthwhile to have at least one test for the getToStringSuccess method and at the very least verifying the tabbing/syntax is correct

2021-01-31 17:37 UTC, zpChris commented on README.md
> +    }
1. Ah, I see -- that makes sense. I think this is likely a good solution 👍 
2. I think this sounds good as well! I think it's good to convert the output of the user's code to the actual object it's intended to be, in case we want to use that for any reason. This means we should also have a standard for converting the string solution in the database to the object.

2021-01-31 17:41 UTC, zpChris commented on src/main/java/com/rocketden/tester/service/generators/PythonDriverGeneratorService.java
>      }
Per [this discussion](https://github.com/rocketden/tester/pull/11#discussion_r567313127), I think this plan sounds good.

2021-01-31 17:43 UTC, zpChris commented on src/test/java/com/rocketden/tester/service/generators/PythonDriverGeneratorServiceTests.java
> +    }
Ok, that sounds good -- we can keep these tests.

2021-01-31 17:48 UTC, zpChris approved these changes
LGTM! I will note that I'm not sure one of the changes from the previous PR was actually finished, so if I'm right be sure to address that before merging. Otherwise though, this PR and the future plans for development sound good!

2021-01-31 17:48 UTC, zpChris commented on src/test/java/com/rocketden/tester/api/JavaTests.java
> +                "###########_SUCCESS_############",
I don't think you finished doing all this? It's changed in the instance below, but not here and not in one example in `PythonTests.java`?

2021-02-01 06:02 UTC, alankbi commented on src/test/java/com/rocketden/tester/api/JavaTests.java
> +                "###########_SUCCESS_############",
Yeah my bad, just fixed the remaining 2 instances of this

2021-02-01 06:02 UTC, merged