Create the Result output data structures.
rocketden/tester pull request #13
Opened 2021-01-31 19:10 UTC by zpChris

### List of Changes:

Add bullet points here.

### Notes:

```
/**

There should be an object that has the console / output / error for each method.
For any result, either the output or the error exists while the other is null.
Maybe a <ResultDto>, with the above fields.
Perhaps this object also holds the correct solution, as well as booleans.
I could also include the PlayerCode object, though I'm uncertain if matters.
Long runtime as well.
I should use startTime, numCorrect, and numTestCases as well.

These are in a List that match

 */
```

### Screencast and Images:

Add your images and/or screencasts here.

2021-01-31 21:56 UTC, zpChris commented
![](https://github.trello.services/images/mini-trello-icon.png) [Create the result output data structure](https://trello.com/c/ybilCESj/258-create-the-result-output-data-structure)

2021-02-01 06:54 UTC, alankbi requested changes
Awesome work! I requested a few changes but overall looks like we're 98% of the way to the MVP :) 

Also, a question: this PR is going to be followed up with 1 (or 2?) PRs right? One remaining thing would be the reading in of the serialized outputs and comparing them using Java objects, and the other would be fixing those test cases once that behavior is implemented (as well as making sure the captureParseOutput logic is being tested, as it currently is not here)

2021-02-01 06:54 UTC, alankbi commented on src/main/java/com/rocketden/tester/service/DockerService.java
> +    public static final String DELIMITER_FAILURE = "###########_FAILURE_############";
Note: after merging in main, I think you should be able to remove these and use the delimiters in OutputParser

2021-02-01 06:54 UTC, alankbi commented on src/main/java/com/rocketden/tester/service/DockerService.java
> +        int testCount = 0;
Is it possible to remove or simplify the way testCount is used? It seems like there's 2 usages of it, 1. `testCases.get(testCount)` and `testCount != testCases.size()`

A potential alternative to both of these is `testCases.get(results.size())` and `results.size() != testCases.size()`, which I feel might help get rid of the need to pass testCount into `parseTestCaseOutput` while also returning testCount from that method.

2021-02-01 06:54 UTC, alankbi commented on src/main/java/com/rocketden/tester/service/DockerService.java
> +                    output.toString(), results, result, testCases, testCount);
Combined with the other comment about testCount, is it possible to simplify this maybe by directly passing in `testCases.get(...)` (since you're not using testCases for any other purpose)? Also, instead of passing in both results and result, maybe you could just pass in result (for it to modify) and then just directly add result to results the next line down?

2021-02-01 06:54 UTC, alankbi commented on src/main/java/com/rocketden/tester/service/DockerService.java
> +        return testCount;
nit: Perhaps move this to the top so that it's more clear when an error occurs? And then also same note about the testCount stuff (see other comment)

2021-02-01 06:54 UTC, alankbi commented on src/main/java/com/rocketden/tester/service/DockerService.java
> +    private RunDto parseCaptureOutput(Process process, Problem problem) throws IOException, InterruptedException {
Maybe move all this output capturing code to the OutputParser class? I think that can help with single responsibility  stuff (docker service handles docker stuff, output parser handles capturing/judging output)

2021-02-01 06:54 UTC, alankbi commented on src/main/java/com/rocketden/tester/dto/RunDto.java
> +    private LocalDateTime startTime;
Could we simplify/remove any number of these fields? For example, not sure what situation status could be false if an ApiException was not already thrown, or also idk if code and language needs to be returned when it'd just be copying them from the request (on main we'll likely also be copying the contents from this response to the Submission object so it's not crucial to have everything in this return if it'll also be on main), or also numTestCases should just be results.size(), and startTime is also calculated on main too (so if we keep it here we'd have to ditch the calculation on main). 

These are just a couple suggestions though - so feel free to take them up on only some/none of them

2021-02-01 21:53 UTC, zpChris commented on src/main/java/com/rocketden/tester/service/DockerService.java
> +    public static final String DELIMITER_FAILURE = "###########_FAILURE_############";
Sounds good -- done!

2021-02-01 21:57 UTC, zpChris commented on src/main/java/com/rocketden/tester/service/DockerService.java
> +        int testCount = 0;
This is a good idea! I removed unnecessary uses of `testCount` and replaced the rest with `results.size()`.

2021-02-01 22:03 UTC, zpChris commented on src/main/java/com/rocketden/tester/service/DockerService.java
> +                    output.toString(), results, result, testCases, testCount);
The first idea sounds great -- done! ✅ 

The only caveat with the second simplification is when `outputSection = OutputSection.START` (essentially, the first line of the decoding file), we should not be adding anything to the `results` list, as the `result` variable is not yet constructed.

I could add an if statement check for this case to see if `result` should be added, but at that point it might be simpler to pass in the `results` object -- I'll leave this up to you, I'm open to implementing this change or leaving it as-is.

2021-02-01 22:05 UTC, zpChris commented on src/main/java/com/rocketden/tester/service/DockerService.java
> +    private RunDto parseCaptureOutput(Process process, Problem problem) throws IOException, InterruptedException {
I think that makes sense -- I'll implement this! 👍

2021-02-01 22:19 UTC, zpChris commented on src/main/java/com/rocketden/tester/dto/RunDto.java
> +    private LocalDateTime startTime;
I'll remove the `status` variable -- I want to note, do I still need the following line:
```
process.waitFor(TIME_LIMIT, TimeUnit.SECONDS);
```
This references [this method](https://docs.oracle.com/javase/8/docs/api/java/lang/Process.html#waitFor-long-java.util.concurrent.TimeUnit-), but I'm not sure why (or why not) it is needed, so I wanted to check when removing it.

It'd be good to have a discussion on this, but I thought of adding the `code`, `language`, and `startTime` variables because I imagined that when the main repository gets this object, in the future, it may store this full object in the database. This would then have all the necessary information (besides the User, Problem, and Game, but those may be able to be found by association / relation?), to be placed directly in the database.

If we took those fields out, we could still construct the relevant object, but that would require defining two classes on the main repository, one for accepting this object and one for placing it in the database. Since this seemed repetitive, I thought perhaps all those fields could be placed in one object here.

2021-02-01 22:19 UTC, zpChris commented on src/main/java/com/rocketden/tester/service/DockerService.java
> +        return testCount;
Makes sense -- done! 👍

2021-02-01 23:43 UTC, zpChris commented on src/main/java/com/rocketden/tester/dto/RunDto.java
> +    private LocalDateTime startTime;
Per our discussion today, I'll remove these unnecessary fields, as on the main repository we'll need both an entity and a DTO class.

2021-02-02 00:02 UTC, zpChris commented on src/main/java/com/rocketden/tester/service/DockerService.java
> +    private RunDto parseCaptureOutput(Process process, Problem problem) throws IOException, InterruptedException {
Ok, I moved it all to the `OutputParser`! I decided not to make it static, as there will probably be a private Gson object in that class, like `InputParser`.

2021-02-02 07:54 UTC, alankbi approved these changes
Looks good to me!

2021-02-02 07:54 UTC, alankbi commented on src/main/java/com/rocketden/tester/service/DockerService.java
> +            OutputParser outputParser = new OutputParser();
nit: Autowire this class

2021-02-02 07:54 UTC, alankbi commented on src/main/java/com/rocketden/tester/service/parsers/OutputParser.java
> +                outputSection = OutputSection.TEST_CASE;
I must say the VSCode line character limit must be pretty intense haha

2021-02-02 07:54 UTC, alankbi commented on src/main/java/com/rocketden/tester/service/DockerService.java
> +                    output.toString(), results, result, testCases, testCount);
No I think what you said makes sense - lets leave it as is then

2021-02-02 16:44 UTC, zpChris commented on src/main/java/com/rocketden/tester/service/parsers/OutputParser.java
> +                outputSection = OutputSection.TEST_CASE;
Haha, yeah it's at 100 but since this is fairly far nested in for loops and if statements, it ends pretty early. Happy to change this convention but yeah, that's why this is split across lines.

2021-02-02 17:18 UTC, zpChris commented on src/main/java/com/rocketden/tester/service/DockerService.java
> +            OutputParser outputParser = new OutputParser();
Whoops, I somehow missed that `OutputParser` is a service class -- it's now autowired, thanks for the correction!

2021-02-02 17:22 UTC, zpChris commented
The code seems to be failing right now when I run the POST request, so I'm investigating now.

2021-02-02 17:43 UTC, zpChris commented
> The code seems to be failing right now when I run the POST request, so I'm investigating now.

I fixed the issue -- I had to add the last remaining test case output _after_ the while loop ended, as there is not a final "test case delimiter" to end the file. The added code is as follows, immediately after the while loop in `OutputParser.java`:

```
// Add the last remaining test case output, if one exists.
parseTestCaseOutput(outputSection,
    output.toString(), results, result,
    testCases.get(results.size()));
```

2021-02-02 18:37 UTC, zpChris commented
I've also fixed some additional errors; I've listed them below:
1. After the console for the result is set, I added a line to clear the `output` variable (otherwise it is included in the user's code result): `output.setLength(0);`.
2. The mechanism to set the number of problems correct was not included, so I added this. However, @alankbi, since the primary method `parseCaptureOutput` is essentially at the limit of its cognitive complexity, I instead passed in `numCorrect` into the helper method where it calculated any increments and returned the result, which I can then direct store in the original method. I know you had commented on this practice previously as clunky, so -- thoughts on this?
3. I fixed some of the tests and added an additional test in Python to make sure it runs correctly if the user's code fails.
4. ...

Note: When checking the equality of solutions, we may want to artifically add an `\n` to the correct test case to match the output of the result object.

2021-02-03 01:10 UTC, zpChris commented
> I do think it's a bit clunky haha - maybe instead if we didn't want to add any more logic to parseCaptureOutput we could simply replace that line with `runDto.setNumCorrect(calculateNumCorrect(results))`? Where calculateNumCorrect is a private helper method that just loops over the results and returns the count. Imo the 0.x% increase in runtime is offset by better readability, but lmk what you think about this/any alternatives as well

Cool, I'll try this out right now -- thanks for responding here. Should I merge after I implement this @alankbi, or should I check with you again?

> This is for current testing purposes right? Cause I know for the follow up PR where we change to use Java equality checks the new lines would prob be trimmed/rendered irrelevant by Gson

That's a good point, that's not really a concern -- thanks!

2021-02-03 01:12 UTC, alankbi commented
> Cool, I'll try this out right now -- thanks for responding here. Should I merge after I implement this @alankbi, or should I check with you again?

Up to you, although I think it's probably good to just merge since it's not too significant or anything

2021-02-03 01:13 UTC, zpChris commented
> Up to you, although I think it's probably good to just merge since it's not too significant or anything

Ok, I'll go with this -- thanks! 👍

2021-02-03 01:23 UTC, merged