Refactor/docker python ruby setup
rocketden/tester pull request #2
Opened 2021-01-03 19:20 UTC by jerry1ye10

### List of Changes:

- configured tester to run python + ruby code
- Set up infrastructure for other languages (currently not working) 
### Notes:
Setup: 
- cd into docker directory and run ```docker-compose up```
- Start up the server
- Run ```curl -X POST -H "Content-Type: application/json"  -d '{"code": "print(1)", "language": "docker_ruby"}' http://localhost:8080/api/v1/runner``` to send a sample post request 
- To run a python script, make language ```"docker_python"```

Other notes: 
- Code hasn't been cleaned up yet (lots of test print statements, etc)... will be cleaned up after all languages are integrated
### Screencast and Images:

Add your images and/or screencasts here.

2021-01-03 23:56 UTC, zpChris commented
Is there a reason you made the branch name with a `/` @jerry1ye10? (`refactor/Docker-python-ruby-setup`)

2021-01-04 00:14 UTC, zpChris requested changes
Requesting some small changes, just nits that are common code practice across all the PRs. Normally I would approve this, but want to make sure it's directed into the other PR and that we know the process of reviewing and whatnot.

Also, how could you call that POST request from a Java file? That's what the additional `DockerService`, `RunnerService`, and `SetupService` files in #1 are used for.

2021-01-04 00:14 UTC, zpChris commented on src/main/java/com/rocketden/tester/docker/ruby/Dockerfile
> +
nit: Remove extra line.

2021-01-04 00:14 UTC, zpChris commented on src/main/java/com/rocketden/tester/docker/ruby/Dockerfile
> +COPY . .
What does this line do? I see two `.`, which I'm not sure what they're both there for.

2021-01-04 00:14 UTC, zpChris commented on src/main/java/com/rocketden/tester/docker/ruby/Dockerfile
> +CMD [ "ruby", "./code/run.sh" ]
nit: Leave a newline at the end of the file.

2021-01-04 00:14 UTC, zpChris commented on src/main/java/com/rocketden/tester/docker/ruby/script.rb
> +puts [[1,2,3], [4,5,nil]]
nit: Leave a newline at the end of the file.

2021-01-13 07:54 UTC, alankbi reviewed
Looks awesome! I don't have any major requested changes or anything, but I did leave some questions in the comments to try and understand things better before approving if that's cool

2021-01-13 07:54 UTC, alankbi commented on script.py
> +print("hello")
Could we delete or move this file?

2021-01-13 07:54 UTC, alankbi commented on src/main/docker/cpp/Dockerfile
> +RUN apt-get -y install clang
Do you know how long this would take to run? Like is this a build step that only takes up time when creating the image, or is it something that runs on creation of each container?

2021-01-13 07:54 UTC, alankbi commented on src/main/docker/python/Dockerfile
> +COPY . .
I saw you had a comment for why this line was needed for running the C stuff, but do we need it here as well (and in other Dockerfiles)?

2021-01-13 07:54 UTC, alankbi commented on src/main/docker/temp/code/script.
> +puts(1,2,3,4,5)
What is this file used for?

2021-01-13 07:54 UTC, alankbi commented on src/main/java/com/rocketden/tester/dto/RunRequest.java
> +    public String getCode(){
nits: Uncomment the getters/setters again and (sorry this may be a bit picky haha) add a space before the brackets (e.g. `getCode() {`

2021-01-13 07:54 UTC, alankbi commented on src/main/java/com/rocketden/tester/service/DockerService.java
> +        return new String[] {"docker", "run", "--rm", "-v", mountPath, "-t", language};
Is the language string (e.g. `docker_ruby`, etc.) what tells Docker which image/Dockerfile to use? If so, is there any way to modify what the string format is (e.g. `RUBY` or `ruby`)?

2021-01-13 07:54 UTC, alankbi commented on src/main/java/com/rocketden/tester/service/SetupService.java
> +        String folder = String.format("%s/%s/%s", pwd, relativePath, generateRandomFolder());
Is there a reason why you moved the generated folder path to inside the docker language folder rather than the original randomized version (i.e. `.../temp/folder152397`)?

2021-01-13 07:54 UTC, alankbi commented on src/main/java/com/rocketden/tester/service/SetupService.java
> +        switch (language){
This may be beyond the scope of the PR, but one thought I have is that this might be good to move into like an enum of some sorts. The way I imagine it is that it'd look kinda of like [this](https://github.com/rocketden/main/blob/master/src/main/java/com/rocketden/main/exception/RoomError.java) with fields like `PYTHON("python", "py")`, and to convert from a language string in a POST request to the enum type, we'd just have to implement a method like [this](https://github.com/rocketden/main/blob/master/src/main/java/com/rocketden/main/model/problem/ProblemDifficulty.java#L11), which would allow strings like "python", "PYTHON", or "pYthON" to all convert to the enum with the associated name (`PYTHON`). Then we can just directly pass the enum object to this class and not have to have a long switch statement

2021-01-13 15:16 UTC, zpChris commented
This PR still says there are merge conflicts -- I'd resolve those, and respond / react and resolve the rest of the comments above.

2021-01-13 21:08 UTC, zpChris commented
![](https://github.trello.services/images/mini-trello-icon.png) [Set up docker to allow running/compiling Java and other languages](https://trello.com/c/txoPrZKE/206-set-up-docker-to-allow-running-compiling-java-and-other-languages)

2021-01-14 21:54 UTC, jerry1ye10 commented on src/main/docker/cpp/Dockerfile
> +RUN apt-get -y install clang
Only takes up time on creation of the container (so running the actual code should be really fast)

2021-01-14 21:55 UTC, jerry1ye10 commented on src/main/docker/python/Dockerfile
> +COPY . .
haha i copied some of the comments over from dockerfiles online do you want me to standardize comments?

2021-01-14 21:56 UTC, jerry1ye10 commented on src/main/docker/temp/code/script.
> +puts(1,2,3,4,5)
Not needed

2021-01-14 21:56 UTC, jerry1ye10 commented on src/main/java/com/rocketden/tester/dto/RunRequest.java
> +    public String getCode(){
Sounds good... got it working but forgot to comment out my self-implemented ones

2021-01-14 21:58 UTC, jerry1ye10 commented on src/main/java/com/rocketden/tester/service/DockerService.java
> +        return new String[] {"docker", "run", "--rm", "-v", mountPath, "-t", language};
Yup and didn't really look into the second but should be pretty easy

2021-01-14 21:58 UTC, jerry1ye10 commented on src/main/java/com/rocketden/tester/service/SetupService.java
> +        String folder = String.format("%s/%s/%s", pwd, relativePath, generateRandomFolder());
I was having some issues with directories from the c++ and c docker containers I'm not completely sure why tbh but this fixed up the problem

2021-01-18 20:30 UTC, zpChris commented
Since @jerry1ye10 is taking a week-long break from the project while he decides what to do, I'm making the necessary changes that remain on this PR.

2021-01-19 02:08 UTC, zpChris commented
I can't figure out how to run Java, so I'm waiting to pair program with @alankbi or @jerry1ye10 (if he is willing). I'll put this PR on hold for the time being.

2021-01-20 04:05 UTC, zpChris commented
I've now tested all of the languages in this PR, and in their current form, they are all working. However, I'm going to try to revise the PR to create and run the files in the `temp` folder as @jerry1ye10 changed the structure, so I will have to test the implementation during this process.

2021-01-20 04:06 UTC, zpChris commented on src/main/java/com/rocketden/tester/service/SetupService.java
> +        switch (language){
This is a great idea -- implementing this now!

2021-01-21 03:09 UTC, zpChris commented on src/main/java/com/rocketden/tester/docker/ruby/Dockerfile
> +
Resolving this conversation as I've cloned the PR and fixed the issue.

2021-01-21 03:09 UTC, zpChris commented on src/main/java/com/rocketden/tester/docker/ruby/Dockerfile
> +COPY . .
Resolving this conversation as I've cloned the PR and fixed the issue.

2021-01-21 03:10 UTC, zpChris commented on src/main/java/com/rocketden/tester/docker/ruby/Dockerfile
> +CMD [ "ruby", "./code/run.sh" ]
Resolving this conversation as I've cloned the PR and fixed the issue.

2021-01-21 03:10 UTC, zpChris commented on src/main/java/com/rocketden/tester/docker/ruby/script.rb
> +puts [[1,2,3], [4,5,nil]]
Resolving this conversation as I've cloned the PR and fixed the issue.

2021-01-21 03:11 UTC, zpChris commented on script.py
> +print("hello")
Done! 👍

2021-01-21 03:11 UTC, zpChris commented on src/main/docker/python/Dockerfile
> +COPY . .
I've cloned the PR and standardized the Dockerfiles.

2021-01-21 03:11 UTC, zpChris commented on src/main/docker/temp/code/script.
> +puts(1,2,3,4,5)
Deleted 👍

2021-01-21 03:12 UTC, zpChris commented on src/main/java/com/rocketden/tester/dto/RunRequest.java
> +    public String getCode(){
This is now fully updated 👍

2021-01-21 03:13 UTC, zpChris commented on src/main/java/com/rocketden/tester/service/SetupService.java
> +        String folder = String.format("%s/%s/%s", pwd, relativePath, generateRandomFolder());
I've now moved the `relativePath` and `folder` variables back to what they were, as well as the location of the `docker` folder.

2021-01-21 03:13 UTC, zpChris commented on src/main/java/com/rocketden/tester/service/SetupService.java
> +        switch (language){
Done 👍

2021-01-21 05:56 UTC, zpChris commented on src/main/java/com/rocketden/tester/service/DockerService.java
> +        return new String[] {"docker", "run", "--rm", "-v", mountPath, "-t", language};
Resolved, simplified this issue by adding a `Language.java` class.

2021-01-21 06:00 UTC, zpChris commented
I've added support for running `javascript` as well, and cleaned up this PR. Re-requested review @alankbi, then next steps we can move to implementing the driver file that runs the user's solution.

2021-01-22 04:37 UTC, alankbi reviewed
Left some nits but approved 👍 

I didn't test every language but I think that could be something that we eventually get to once we flesh out the design with a subset of languages first

2021-01-22 04:37 UTC, alankbi commented on src/main/java/com/rocketden/tester/docker/docker-compose.yml
> +    build: ./c
Since we're only going to be using 1 or 3-4 languages in the near future, thoughts on commenting the more niche languages out for now? That might save on some of the build time when testing

2021-01-22 04:37 UTC, alankbi commented on src/main/java/com/rocketden/tester/docker/java/Dockerfile
> +CMD ["/start.sh"]
Do you need both of these lines? I noticed some of the other files didn't have `ENTRYPOINT`

2021-01-22 04:37 UTC, alankbi commented on src/main/java/com/rocketden/tester/exception/DockerSetupError.java
> +    BUILD_DOCKER_CONTAINER(HttpStatus.INTERNAL_SERVER_ERROR, "The program unexpectedly failed to create a docker container.");
Do we need to have separate error messages for each of these? I think it's def not an issue for this PR, although I can imagine in the future these errors will quickly grow in number without the users necessarily needing to know where it went wrong

2021-01-22 04:37 UTC, alankbi commented on src/main/java/com/rocketden/tester/model/Language.java
> +    }
Thoughts on changing it so that `this.dockerContainer = String.format("docker_%s", this.name().toLowerCase()`? That might simplify the logic so we don't have to specify "docker_xxx" for each enum, although if you think there might be issues with the name not matching the docker name I'm totally fine with it as is too

2021-01-22 04:37 UTC, alankbi commented on src/main/java/com/rocketden/tester/model/Language.java
> +    BASH("docker_bash", "sh");
nit: put each enum on a separate line (unless there's an IDE warning that I missed on or something)

2021-01-22 04:37 UTC, alankbi commented on src/main/java/com/rocketden/tester/service/SetupService.java
> +        return RandomStringUtils.randomAlphanumeric(10);
Thanks for doing this haha

2021-01-23 01:10 UTC, zpChris commented on src/main/java/com/rocketden/tester/docker/docker-compose.yml
> +    build: ./c
Sure -- I included only Python, Java, and JavaScript, since they don't take that much space and we'll likely use for testing in the future. The next ones I would add are C and C++, but since those take space I won't include them here.

2021-01-23 01:10 UTC, zpChris commented on src/main/java/com/rocketden/tester/docker/java/Dockerfile
> +CMD ["/start.sh"]
Testing this it did seem I specifically needed to include `ENTRYPOINT` -- I'm not sure why, but I found this when testing with @jerry1ye10.

2021-01-23 01:11 UTC, zpChris commented on src/main/java/com/rocketden/tester/exception/DockerSetupError.java
> +    BUILD_DOCKER_CONTAINER(HttpStatus.INTERNAL_SERVER_ERROR, "The program unexpectedly failed to create a docker container.");
I think it would be useful just for error reporting on our end; if we ever keep track of where exactly things are failing if we start to get failures, then this would be useful. Nevertheless, I see your point, so if this expands too much in the future we can reassess this.

2021-01-23 01:18 UTC, zpChris commented on src/main/java/com/rocketden/tester/model/Language.java
> +    }
Good idea! If it turns out that any language in the future doesn't obey the "docker_xxx" rule, we'll need to change this back -- but for now, updated!

2021-01-23 01:19 UTC, zpChris commented on src/main/java/com/rocketden/tester/model/Language.java
> +    BASH("docker_bash", "sh");
Done!

2021-01-23 01:20 UTC, zpChris commented on src/main/java/com/rocketden/tester/service/SetupService.java
> +        return RandomStringUtils.randomAlphanumeric(10);
For sure 👍

2021-01-23 01:23 UTC, zpChris approved these changes
LGTM!

(Note: This PR was made by both @jerry1ye10 and I, but I reviewed and approved anyway since I couldn't seem to remove myself from the reviewers list.)

2021-01-23 01:30 UTC, alankbi approved these changes

2021-01-23 01:42 UTC, merged