Add Problem IO Type and toString conversion for instantiation and initialization.
rocketden/tester pull request #7
Opened 2021-01-26 02:08 UTC by zpChris

### List of Changes:

- Add the `ProblemIOType` class, include a setup to get class name.
- Add methods `typeInstantiationToString` and `typeInitializationToString`, implemented for Java and Python.
- Add many tests for the `toString` functions of instantiation and initialization.

### Notes:

- I changed the `ProblemIOType` class enum elements from the main repository, as well as added a Class field which helps with conversion `toString`.
- I'm not sure the `ProblemIOType` field of `typeInitializationToString` is really necessary -- the function could be completed without it, so let me know @alankbi.
- I'm not sure how important the tests are for this PR -- I think it could be argued to remove them, especially for the non-array objects.
  - Additionally, the expected answers are hard-coded for these results, which doesn't make sense for many of these where there are fields -- but it'd be weird to populate them as well, because that wouldn't be testing anything. So this is again related to the importance of the tests, let me know if I should include them.
  - Small note: The `double` object converts to have many decimal points; I haven't worked to solve this as it won't actually matter in implementation, it's just a visual thing.

### Screencast and Images:

There are no changes to the UI, and those no screencasts or images attached.

2021-01-26 02:15 UTC, zpChris commented
![](https://github.trello.services/images/mini-trello-icon.png) [Create map from string to data structures for how code is run](https://trello.com/c/QaWRvSfD/200-create-map-from-string-to-data-structures-for-how-code-is-run)

2021-01-26 07:21 UTC, alankbi requested changes
Looks great! I don't think I really had major changes, but I requested changes just to be safe (so we can make sure to discuss everything needed)

Just to clarify what the workflow is based on what I see in this PR and envision: 

1. Request contains the problem info with the method name, param types, etc. 
2. Temp folder is setup and calls driver service to set up driver file
3. The correct driver generator class is called with the problem info
4. For each test case, it will get a list of `Object` items, each `Object` being of the proper type specified in ProblemIOType (this getting method to-be-implemented)
5. It will generate all the variables and finish up the rest of it

Lmk if that's what you had in mind or you imagined something else

2021-01-26 07:21 UTC, alankbi commented on src/main/java/com/rocketden/tester/service/DriverGeneratorService.java
> +    String typeInitializationToString(ProblemIOType ioType, Object value);
Given that the first method is not needed for certain languages, should the first one (or even both) be included in the interface? Since they're only relevant internally and not used publically by any situations, maybe that could be left up to the implementation of each language's driver generator file? Although I can see the benefit of standardization esp. with tricky code like this

2021-01-26 07:21 UTC, alankbi commented on src/main/java/com/rocketden/tester/service/generators/JavaDriverGeneratorService.java
> +            return null;
Maybe throw an exception here and in default?

2021-01-26 07:21 UTC, alankbi commented on src/main/java/com/rocketden/tester/service/generators/JavaDriverGeneratorService.java
> +            case ARRAY_INTEGER:
I saw there were a lot of test cases but just want to confirm - do these casts function properly? And do they require perfect matches e.g. int[] vs. Integer or Double vs. double?

2021-01-26 07:21 UTC, alankbi commented on src/test/java/com/rocketden/tester/service/generators/JavaDriverGeneratorServiceTests.java
> +    }
I saw you mentioned that point about these test cases and I prob would agree - maybe in the future once we fully implement these generator files it might be easier if we just had like a pre-written Java file and confirmed that the generator produces the exact same result - or something like that (but I'm open to ideas on this too)

2021-01-26 07:21 UTC, alankbi commented on src/test/java/com/rocketden/tester/service/generators/JavaDriverGeneratorServiceTests.java
> +    public void typeInitializationToStringNullError() {
although I think it could be useful to keep these error check tests

2021-01-26 22:25 UTC, zpChris commented on src/main/java/com/rocketden/tester/model/problem/Problem.java
> +    private Map<String, ProblemIOType> inputNameTypeMap;
That's a good point that the order will be important -- I will implement some custom pair class.

2021-01-26 22:26 UTC, zpChris commented
> Looks great! I don't think I really had major changes, but I requested changes just to be safe (so we can make sure to discuss everything needed)
> 
> Just to clarify what the workflow is based on what I see in this PR and envision:
> 
> 1. Request contains the problem info with the method name, param types, etc.
> 2. Temp folder is setup and calls driver service to set up driver file
> 3. The correct driver generator class is called with the problem info
> 4. For each test case, it will get a list of `Object` items, each `Object` being of the proper type specified in ProblemIOType (this getting method to-be-implemented)
> 5. It will generate all the variables and finish up the rest of it
> 
> Lmk if that's what you had in mind or you imagined something else

I think this is all correct!

2021-01-26 22:29 UTC, zpChris commented on src/main/java/com/rocketden/tester/model/problem/Problem.java
>      private String methodName;
That's a good point -- I'll change this to a Map from Language to methodName. I'll also note that @helenli8181 will likely have to change that on her PR when she constructs it on the main repository.

2021-01-26 22:30 UTC, zpChris commented on src/main/java/com/rocketden/tester/model/problem/ProblemIOType.java
> +        return value.getClass().equals(this.getClassType());
This is a good question -- I was thinking that for the actual Java handling, we would only use the Object versions of those primitives, so in my mind we shouldn't have to worry about whether they do or not.

2021-01-26 22:32 UTC, zpChris commented on src/main/java/com/rocketden/tester/service/DriverGeneratorService.java
> +    String typeInitializationToString(ProblemIOType ioType, Object value);
In my mind, the first method is used by enough languages that it makes sense to include it in the interface instead of having that be an auxilary method in the implementing classes -- I'm open to further discussion on this though.

2021-01-26 22:32 UTC, zpChris commented on src/main/java/com/rocketden/tester/service/generators/JavaDriverGeneratorService.java
> +            return null;
Sounds good! 👍

2021-01-26 22:34 UTC, zpChris commented on src/main/java/com/rocketden/tester/service/generators/JavaDriverGeneratorService.java
> +            case ARRAY_INTEGER:
They do function properly, I believe the tests confirm that. As for the second question, see [my reply here](https://github.com/rocketden/tester/pull/7#discussion_r564878726).

2021-01-26 22:34 UTC, zpChris commented on src/test/java/com/rocketden/tester/service/generators/JavaDriverGeneratorServiceTests.java
> +    }
Sounds good -- should I remove all the "instantiation" tests (except checking for an error)?

2021-01-26 22:35 UTC, zpChris commented
@alankbi -- thoughts on the following from the notes?

> - I'm not sure the `ProblemIOType` field of `typeInitializationToString` is really necessary -- the function could be completed without it, so let me know @alankbi. I'm expecting I may have to re-do this, and there are several ways to, but I wanted to get your impression on the overall PR before I start delving in deeper.

2021-01-27 00:02 UTC, zpChris commented on src/main/java/com/rocketden/tester/model/problem/Problem.java
>      private String methodName;
Done!

2021-01-27 00:13 UTC, zpChris commented on src/main/java/com/rocketden/tester/model/problem/Problem.java
> +    private Map<String, ProblemIOType> inputNameTypeMap;
I implemented the `ProblemInput` object, and then changed this field to be of the type `List<ProblemInput>`. (I also updated #9 with this new setup) 👍

2021-01-27 00:46 UTC, zpChris commented
I also added `LanguageTests.java` and `ProblemTests.java` files to test the `fromString` methods.

2021-01-27 00:52 UTC, zpChris commented on src/test/java/com/rocketden/tester/service/generators/JavaDriverGeneratorServiceTests.java
> +    }
Ok, I removed almost all of the "instantiation" tests, leaving one for testing and another String one. If you think I should change this or add anything back, let me know.

2021-01-27 08:35 UTC, alankbi commented on src/main/java/com/rocketden/tester/model/problem/Problem.java
>      private String methodName;
This kind of ties in with the other comment which is that I'm not sure how well JSON/post requests can handle maps? And also I'd be a little hesitant to require users to specify the method name for each language

Not sure that I have a better solution haha, but maybe is it possible to do some kinda of dynamic initialization? Maybe if methodName was like a space separated name like "find max" or a list [find, max] and based on different languages it could chain them together in camel case, snake case, etc. just throwing some ideas out there

2021-01-27 08:36 UTC, alankbi commented on src/main/java/com/rocketden/tester/service/DriverGeneratorService.java
> +    String typeInitializationToString(ProblemIOType ioType, Object value);
Sounds good to me

2021-01-27 08:39 UTC, alankbi commented
> @alankbi -- thoughts on the following from the notes?
> 
> > * I'm not sure the `ProblemIOType` field of `typeInitializationToString` is really necessary -- the function could be completed without it, so let me know @alankbi. I'm expecting I may have to re-do this, and there are several ways to, but I wanted to get your impression on the overall PR before I start delving in deeper.

Could you elaborate on this? I looked through those methods and it seems like it's being used in both of them - unless you mean there might be better ways of doing it that are type-agnostic or something (which would be amazing haha)?

2021-01-27 08:45 UTC, alankbi approved these changes
Looks good! Two remaining nits but other than that it looks good to go for me

2021-01-27 08:45 UTC, alankbi commented on src/test/java/com/rocketden/tester/api/LanguageTests.java
> +    }
nit: move this and ProblemTests to a different folder, maybe like a new `models` folder to correspond with their locations in main (this tester repo's main branch's main folder lol)

2021-01-27 08:45 UTC, alankbi commented on src/test/java/com/rocketden/tester/service/generators/JavaDriverGeneratorServiceTests.java
> +    }
Tbh I think once we implement like the full-driver file generation test these might also be okay to pass on haha - for now tho I think these look good

2021-01-27 20:45 UTC, zpChris commented on src/test/java/com/rocketden/tester/service/generators/JavaDriverGeneratorServiceTests.java
> +    }
Haha ok, that sounds good 👍

2021-01-27 22:26 UTC, zpChris commented
> Could you elaborate on this? I looked through those methods and it seems like it's being used in both of them - unless you mean there might be better ways of doing it that are type-agnostic or something (which would be amazing haha)?

A couple options:
1. For the switch-case function in this method, I could maybe case instead on the literal `Object` type / name, as follows:
```
switch (value.getClassType().getSimpleName()) {
  case "String":
    return String.format("\"%s\"", (String) value);
  ...
```
2. I could also add a `Map<Class<?> class, ProblemIOType type> typeClassMap` in the `ProblemIOType` class, and then do the following:
```
ProblemIOType type = typeClassMap.get(value.getClass());
if (type == null) {
  throw [some exception];
}
[continue with switch statement]
```

I'm open to keeping it or changing it, as I'm not sure which is the best design. I might lean towards (2), but what do you think @alankbi?

2021-01-27 22:29 UTC, zpChris commented on src/test/java/com/rocketden/tester/api/LanguageTests.java
> +    }
Done! ✅

2021-01-28 05:14 UTC, alankbi commented
> A couple options:
>  ...
> I'm open to keeping it or changing it, as I'm not sure which is the best design. I might lean towards (2), but what do you think @alankbi?

Personally I'm okay with just leaving it as is - I feel like the extra parameter in the method is not too big a deal and is prob worth it to save on the overhead of creating a separate mapping - of the two options though I'd also prob lean towards 2 as well

2021-01-28 06:05 UTC, alankbi commented on src/main/java/com/rocketden/tester/model/problem/Problem.java
>      private String methodName;
Another thing - this might also apply to method parameter names right? e.g. `method(numArray)` vs. `method(num_array)`

2021-01-28 06:06 UTC, alankbi commented on src/main/java/com/rocketden/tester/model/problem/Problem.java
>      private String methodName;
If so, I'd be okay with leaving that for a separate PR since it's likely not just a quick and easy fix

2021-01-28 15:18 UTC, zpChris commented on src/main/java/com/rocketden/tester/model/problem/Problem.java
>      private String methodName;
> Not sure that I have a better solution haha, but maybe is it possible to do some kinda of dynamic initialization? Maybe if methodName was like a space separated name like "find max" or a list [find, max] and based on different languages it could chain them together in camel case, snake case, etc. just throwing some ideas out there

Per our conversation yesterday, I think this is a good idea -- I'll try to implement this; I'll likely request review again haha because the changes will be relatively significant.

> Another thing - this might also apply to method parameter names right? e.g. method(numArray) vs. method(num_array)

This is an interesting point -- I looked across 5+ LeetCode problems and didn't find this (they all seemed to be "single words" and the same across different languages), with one notable exception: C. For C, they pass in pointers instead of arrays, so they also have to pass in _additional_ parameters to hold the number of elements present at the pointer. (This obviously causes more parameter names, but they seem to be systematically based off of the original name; if the output is an array, the function also passes in the `returnSize`.) [[1]](https://leetcode.com/problems/two-sum/) [[2]](https://leetcode.com/problems/symmetric-tree/)

I'll plan on leaving this problem to another PR, but maybe we can talk about it tonight, as C (and C++, which I think has some of these issues) is definitely a popular language we'll want to account for.

2021-01-28 20:08 UTC, zpChris commented on src/main/java/com/rocketden/tester/model/problem/Problem.java
>      private String methodName;
[Binary Search](https://binarysearch.com/problems) just makes the method equal `solve` always -- could we do this? Seems like a simple solution, and it would work for all languages.  The only downside I can think of is if somebody in Github is trying to combine their solutions into one file -- though I think these people would use separate files, so I'm not sure this is actually a concern.

2021-01-28 22:09 UTC, zpChris commented on src/main/java/com/rocketden/tester/model/problem/Problem.java
>      private String methodName;
Confirmed that this is OK with @alankbi offline, so I'll make this change and merge.

2021-01-28 22:11 UTC, merged