Implement test structure and first preliminary tests
rocketden/tester pull request #8
Opened 2021-01-26 07:50 UTC by alankbi

### List of Changes:

* Add integration (API) test and unit test files for existing codebase
* Implement several test cases for SetupService, RunnerService, and other classes
* Create files and basic environment setup for classes that need future test coverage

### Notes:

* As of now, the API and generator tests are left blank as I think we need to wait a bit for those to be fleshed out
* RunnerService, SetupService, and some failure tests are implemented (mostly) up to standard (my standards at least lol)
* DockerService is also left blank because it's hard to test (although should be well covered by integration tests by default)

2021-01-26 07:51 UTC, alankbi commented
![](https://github.trello.services/images/mini-trello-icon.png) [Create test structure and preliminary tests for tester service](https://trello.com/c/pPxQDPg9/247-create-test-structure-and-preliminary-tests-for-tester-service)

2021-01-26 21:43 UTC, zpChris commented
> some failure tests are implemented (mostly) up to standard (my standards at least lol)

Lots of qualifiers there haha 😄

2021-01-26 22:23 UTC, zpChris requested changes
Requesting changes as some of the tests seem to be failing, and I don't think some of these files are necessary. Otherwise, these tests look great though!

2021-01-26 22:23 UTC, zpChris commented on src/test/java/com/rocketden/tester/api/RunnerTests.java
> +        String jsonRequest = "{\"code\": \"print('hi')\", \"language\": \"js\", \"problem\": \"{}\"}";
I believe this test fails because there is no language called "js", right -- it's actually called "javascript"? If so, I feel like it'd be better to make this clearer by just making a fake language or a clear typo like "notjava".

2021-01-26 22:23 UTC, zpChris commented on src/test/java/com/rocketden/tester/api/RunnerTests.java
> +    private static final Language LANGUAGE = Language.JAVA;
Remove these fields, as these aren't necessary for the test (as it's currently set up).

2021-01-26 22:23 UTC, zpChris commented on src/test/java/com/rocketden/tester/service/RunnerServiceTests.java
> +        verify(setupService).deleteTempFolder(TEMP_FOLDER);
This was not invoked on when I ran this test locally -- does this test pass for you?

2021-01-26 22:23 UTC, zpChris commented on src/test/java/com/rocketden/tester/service/generators/JavaDriverGeneratorServiceTests.java
> +package com.rocketden.tester.service.generators;
Note: I implement tests in this file, and `PythonDriverGeneratorServiceTests.java`, in #9 -- so I have no preference if you keep or delete these files (either way works great).

2021-01-26 22:23 UTC, zpChris commented on src/test/java/com/rocketden/tester/util/UtilityTestMethods.java
> +}
nit: Add ending newline.

2021-01-26 22:23 UTC, zpChris commented on tester.iml
> +    <orderEntry type="library" scope="TEST" name="Maven: com.google.code.gson:gson:2.8.6" level="project" />
I don't remember having to add these in the main repository -- is this just bad memory or is this for some reason only necessary in `tester.iml`?

2021-01-27 09:40 UTC, alankbi commented on src/test/java/com/rocketden/tester/service/DockerServiceTests.java
> +package com.rocketden.tester.service;
I'm not mad about skipping these tests at all lol

2021-01-27 09:48 UTC, alankbi commented on src/test/java/com/rocketden/tester/service/RunnerServiceTests.java
> +        verify(setupService).deleteTempFolder(TEMP_FOLDER);
Fixed - I forgot to implement a try-finally block to make the cleanup occur regardless of error (I think you mentioned it in an earlier PR)

2021-01-27 09:49 UTC, alankbi commented on src/test/java/com/rocketden/tester/service/generators/JavaDriverGeneratorServiceTests.java
> +package com.rocketden.tester.service.generators;
Sounds good - it'll probably get resolved after merging it all

2021-01-27 09:50 UTC, alankbi commented on tester.iml
> +    <orderEntry type="library" scope="TEST" name="Maven: com.google.code.gson:gson:2.8.6" level="project" />
Yeah no this is an auto-generated file so this isn't relevant to any functioning code stuff

2021-01-27 09:50 UTC, alankbi commented on src/test/java/com/rocketden/tester/api/JavaTests.java
> +    public void runRequestSuccess() throws Exception {
Response in other thread so I'll resolve this one

2021-01-27 09:52 UTC, alankbi commented on src/test/java/com/rocketden/tester/api/PythonTests.java
> +	public void runRequestSuccess() throws Exception {
Yeah these tests as of now fail - when I wrote them, the driver files were hardcoded and I didn't want to create tests that would only work temporarily. However now that we have the driver code (mostly) working I'll merge the branches and get these ones to pass (although once we figure out the output capturing and flesh out the RunDto return object these tests will have to be updated again)

2021-01-27 20:42 UTC, zpChris commented on src/test/java/com/rocketden/tester/api/PythonTests.java
> +	public void runRequestSuccess() throws Exception {
Makes sense and sounds good -- if you wanted to just remove that test or leave it blank until that full process is fully implemented I'd be OK with that, but if you want to update them as we update the codebase that's cool too, your choice 👍

2021-01-28 07:14 UTC, alankbi commented
Re-requesting review - I pulled the latest changes from `AddProblemDynamic` (also changed this PR to merge into that branch) and since now the driver file stuff mostly works, I implemented several additional tests and error validation checks (so feel free to request changes again cause there's some new stuff)

2021-01-28 17:39 UTC, zpChris approved these changes
LGTM!

I left some comments and nits, but nothing big, and I'm confident you can make the relevant changes (or decide that they're unnecessary).

2021-01-28 17:39 UTC, zpChris commented on src/main/java/com/rocketden/tester/service/SetupService.java
>      public String createTempFolder(RunRequest request) {
Could this function throw an error _after_ it creates the temp folder, but perhaps before it makes the driver or solution file? If so, maybe we could add the `deleteTempFolder` function in the inner try-catch block? (I would comment directly there but Github won't let me.)

2021-01-28 17:39 UTC, zpChris commented on src/main/java/com/rocketden/tester/service/RunnerService.java
> +            setupService.deleteTempFolder(folder);
Thanks for doing this! Good solution ✅

2021-01-28 17:39 UTC, zpChris commented on src/test/java/com/rocketden/tester/api/JavaTests.java
> +import java.util.Map;
nit: Remove unused imports.

2021-01-28 17:39 UTC, zpChris commented on src/test/java/com/rocketden/tester/api/JavaTests.java
> +import com.rocketden.tester.model.problem.ProblemTestCase;
nit: Remove unused imports.

2021-01-28 17:39 UTC, zpChris commented on src/test/java/com/rocketden/tester/api/JavaTests.java
> +            "",
This reminds me that we may want to add `import java.util.*;` to the start of every file for the user's code (on frontend and backend) as well.

2021-01-28 17:39 UTC, zpChris commented on src/test/java/com/rocketden/tester/api/JavaTests.java
> +    public void runRequestSuccess() throws Exception {
nit, just an idea: If possible, either in `JavaTests.java` or `PythonTests.java`, could we add tests that verify the Console and Error portions work as well?

I'm not actually sure if this is necessary just because I know this format will change, so I'm 100% ok if we want to go ahead with this test (also because there are 600+ line changes) -- however, I wanted to note it down at least for the future.

2021-01-28 17:39 UTC, zpChris commented on src/test/java/com/rocketden/tester/api/PythonTests.java
> +			"class Solution:",
This is forward-looking -- similar to Java with `import java.util.*;`, are there any imports we should initially place into the user's file that have commonly-used functions?

2021-01-28 17:39 UTC, zpChris commented on src/test/java/com/rocketden/tester/service/SetupServiceTests.java
> +        // Cleanup any files created (note: this will not always be reached if failures occur)
This relates to one of my notes above, but maybe we include `deleteTempFolder` in the exceptions as well to prevent this edge case from happening?

2021-01-28 17:39 UTC, zpChris commented on src/test/java/com/rocketden/tester/service/SetupServiceTests.java
> +    public void deleteTempFolderInvalidFolder() {
nit: Perhaps test the `DockerSetupError.DELETE_TEMP_FOLDER` error as well?

2021-01-28 17:39 UTC, zpChris commented on src/test/java/com/rocketden/tester/util/UtilityTestMethods.java
> +        Gson gson = new Gson();
I know we have the same setup in the main repository, and I may have asked this question before, but could we add the GSON object as a static field in this class?

2021-01-28 17:39 UTC, zpChris commented on src/test/java/com/rocketden/tester/util/ProblemTestMethods.java
> +        );
Heads up, per our conversation, you may need to update this if I change the base branch #7.

2021-01-28 17:41 UTC, zpChris commented
One more overall nit: There are also some unused imports in `RunnerTests.java`. Do you have a linter that checks for unused imports? No problem if not, just wanted to check ✔️

2021-01-29 08:33 UTC, alankbi commented on src/main/java/com/rocketden/tester/service/SetupService.java
>      public String createTempFolder(RunRequest request) {
This is referring to if the createTempFolder method fails halfway through right? If so, I split createTempFolder to add an additional method populateTempFolder, which handles the writing of the driver and solution files. This way, createTempFolder can handle just creating and returning the folder name (which we need in order to be able to call delete on the correct location), and then the populating of file can be included in the try catch block so that the finally block will be executed

2021-01-29 08:39 UTC, alankbi commented on src/test/java/com/rocketden/tester/api/PythonTests.java
> +			"class Solution:",
Good question - I don't use Python for LeetCode-type stuff enough to know if there's anything absolutely critical, but I guess based on that fact I think it should be good? But yeah def important to remember for other languages that might need them

2021-01-29 08:48 UTC, alankbi commented on src/test/java/com/rocketden/tester/api/JavaTests.java
> +    public void runRequestSuccess() throws Exception {
Yeah, I think it'd def be good to have those (though prob implemented later once we implement the proper output parsing RunDto responses). There's a test stub for error occurred but I'll add ones too for testing console output

2021-01-29 08:49 UTC, alankbi commented on src/test/java/com/rocketden/tester/service/SetupServiceTests.java
> +        // Cleanup any files created (note: this will not always be reached if failures occur)
I'm not sure if I totally understand the exceptions part, but I did move this code into a try finally block so the deleteTempFolder should now always execute (same thing for the main codebase as we talked about in different comments)

Lmk if you had something else in mind and I can implement that as well (tho maybe in the next PR if this one gets merged before then haha)

2021-01-29 08:53 UTC, alankbi commented on src/test/java/com/rocketden/tester/util/ProblemTestMethods.java
> +        );
Sounds good, I'll merge main into this branch (it doesn't show any warnings/merge conflicts on GitHub which is concerning given that I immediately get a compilation error locally after merging haha)

2021-01-29 09:05 UTC, alankbi commented on src/test/java/com/rocketden/tester/service/SetupServiceTests.java
> +    public void deleteTempFolderInvalidFolder() {
I haven't been able to get that code to really fail based on any of our use cases - it requires us to catch the IOException which is why I added the ApiError, but imo given that it's a production-ready package I feel like we might be able to get away with not testing that

I wasn't overly rigorous on playing around with it tho so if in the future it might be useful then I'd def be down on adding some kind of test for that

2021-01-29 09:09 UTC, alankbi commented
> One more overall nit: There are also some unused imports in `RunnerTests.java`. Do you have a linter that checks for unused imports? No problem if not, just wanted to check ✔️

Removed them - I do have linting haha although I guess I'm prone to miss them at times

Also, there were another few decent rounds of changes made - I'll merge this for now, but if you notice anything feel free to comment and I can address those in future PRs

2021-01-29 09:09 UTC, merged