Implement the dynamically-produced driver file for Java and Python.
rocketden/tester pull request #9
Opened 2021-01-26 17:26 UTC by zpChris

### List of Changes:

- Implement the dynamically-produced driver file for Java and Python, based from the Problem in the Postman request.
- Update the `Problem` class (and others) to only include the relevant fields.
- Use GSON (added to `pom.xml`) to convert the String input from the Problem to the relevant object.

### Notes:

- This setup is ideal for test variables that only need a _single line_ for both instantiation and initialization (i.e., _not_ using `list.add([input])`); this works for our current Problem IO Types, and I think we can preserve this invariant, but it may require more creative solutions in the future.
- GSON may not work for all future examples of converting the String input from the Problem to the relevant object; however, I included it here as a starting point. In the future, we may have a different service class that handles this task (conversion both ways, from string -> object and object -> string).

### Screencast and Images:

There are no changes to the UI and thus no screencasts or images are attached.

2021-01-26 17:29 UTC, zpChris commented
I saw you requested changes on #7, so I'll be sure to address those when I can; nevertheless, from what I can tell, if you want you should be able to review this PR as well.

2021-01-26 17:34 UTC, zpChris commented
![](https://github.trello.services/images/mini-trello-icon.png) [Incorporate Problem variables and methods into DriverGeneratorService](https://trello.com/c/JcmmhJS8/246-incorporate-problem-variables-and-methods-into-drivergeneratorservice)

2021-01-27 09:10 UTC, alankbi requested changes
Awesome work! Left some comments but it looks like we're making some great progress so far

2021-01-27 09:10 UTC, alankbi commented on src/main/java/com/rocketden/tester/service/generators/JavaDriverGeneratorService.java
> +            writer.write("\t\t}\n");
This might change depending on the whole file writer thing, but since this part has only 1-2 params (can't tell if that's 1 or 2 on line 135), could we try out one of those multi-string solutions talked about in one of the earlier PRs? Like just to see if something like this might help with readability:

```java
String temp = String.join("\n",
           "} catch (Exception e) {",
           "    System.out.println(...);",
           "    e.printStackTrace();",
           "}");

```

Also this might apply to other places too although I just decided to leave this comment here for now

2021-01-27 09:10 UTC, alankbi commented on src/main/java/com/rocketden/tester/service/generators/JavaDriverGeneratorService.java
> +        for (ProblemTestCase testCase : problem.getTestCases()) {
Any reason for not using a normal for loop?

2021-01-27 09:10 UTC, alankbi commented on src/main/java/com/rocketden/tester/service/generators/PythonDriverGeneratorService.java
> +            writer.write("\t\ttraceback.print_exc()\n\n");
No other comments on this file besides some of the stuff that might carry over from the Java one

2021-01-27 23:00 UTC, zpChris commented on src/main/java/com/rocketden/tester/service/generators/PythonDriverGeneratorService.java
> +        writer.write(String.format("from Solution import %s%n%n", params[0]));
You're right, I fixed this so it imports the class and changed the Postman request to match LeetCode's setup. Thanks!

2021-01-27 23:02 UTC, zpChris commented on src/main/java/com/rocketden/tester/service/generators/JavaDriverGeneratorService.java
> +        writer.write("\t\tSolution solution = new Solution();\n");
That's a good point! Yeah, I'll take your advice and change the method call to `new Solution().methodName(...)`.

2021-01-27 23:13 UTC, zpChris commented on src/main/java/com/rocketden/tester/service/generators/JavaDriverGeneratorService.java
> +            writer.write("\t\t}\n");
I'm hesitant to use spaces instead of `\t` as that would be inconsistent, but I'm ok with using `String.join` and the multi-line approach. I'll implement that where it helps.

Note: That is just one on line 135, the `%n` is a newline -- if you put `\n` in a `String.format` string, it gives you a syntax warning.

2021-01-27 23:39 UTC, zpChris commented on src/main/java/com/rocketden/tester/service/generators/JavaDriverGeneratorService.java
> +            writer.write("\t\t}\n");
Made the changes -- let me know your thoughts 👍

2021-01-27 23:44 UTC, zpChris commented on src/main/java/com/rocketden/tester/service/generators/JavaDriverGeneratorService.java
> +        for (ProblemTestCase testCase : problem.getTestCases()) {
None, good catch -- changed to a normal for loop! 👍

2021-01-27 23:50 UTC, zpChris commented on src/main/java/com/rocketden/tester/service/DriverGeneratorService.java
> +    void writeEndingBoilerplate(FileWriter writer) throws IOException;
What's the benefit of doing this? If we used String it would likely take a longer amount of time, and if we used StringBuilder it would just take about the same amount of time. Since we know that we are definitely writing this code to the file and not sharing it anywhere else (if there is an alternative use for the code, then this would change), isn't saving it to a String or StringBuilder an extra intermediary step?

I'm not sure if this helps, but there are less `writer.write` calls since I used `String.join`.

2021-01-28 05:31 UTC, alankbi commented on src/main/java/com/rocketden/tester/service/DriverGeneratorService.java
> +    void writeEndingBoilerplate(FileWriter writer) throws IOException;
I think removing the responsibility of having to initialize a file writer and handling IO exceptions would be helpful (especially cause it'd have to be reimplemented across every language file). However I'm not overly opinionated on this so I'm okay to just leave it as is for now

2021-01-28 05:33 UTC, alankbi commented on src/main/java/com/rocketden/tester/service/generators/JavaDriverGeneratorService.java
> +            writer.write("\t\t}\n");
Haha it wasn't as great as I imagined in some situations (I think the String.format kinda messed with the alignment) but overall hopefully that can help us in some scenarios

2021-01-28 05:34 UTC, alankbi approved these changes
Looks good to me 👍

2021-01-28 17:42 UTC, zpChris commented on src/main/java/com/rocketden/tester/service/DriverGeneratorService.java
> +    void writeEndingBoilerplate(FileWriter writer) throws IOException;
Ok, I think I'll likely leave this for now then -- but I'm fine if you want to change it on a future PR, I'm just not really sure how the changes would look here.

2021-01-28 17:42 UTC, zpChris commented
Awesome -- I'll wait until I fix #7 to merge this. 👍

2021-01-28 22:16 UTC, merged